FILES = CHIP-8.cpp
CC = g++

SRC_PATH = .
INCLUDE_PATHS = -I$(SRC_PATH)\SDL2-2.0.16\i686-w64-mingw32\include\SDL2
LIBRARY_PATHS = -L$(SRC_PATH)\SDL2-2.0.16\i686-w64-mingw32\lib

COMPILER_FLAGS = -w
LINKER_FLAGS = -lmingw32 -lSDL2main -lSDL2
FILE_NAME = CHIP-8

all : $(FILES)
	$(CC) $(FILES) $(INCLUDE_PATHS) $(LIBRARY_PATHS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(FILE_NAME)